--To find the Location or region
SELECT CURRENT_REGION();

--To Describer File Format
DESC FILE FORMAT SALE_CSV_FORMAT
SHOW FILE FORMATS

--To Describer Storage Integration
DESC STORAGE INTEGRATION AWS_INT
DESC INTEGRATION AWS_S3_INTEGRATION
